[package]
name = "bloom"
version = "0.1.0"
authors = ["nettee <nettee.liu@gmail.com>"]
edition = "2018"
description = "Blog output manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
toml = "0.5.3"